### ISSUE TITLE
Designed strategies can't be created

### ISSUE THREAD

**Issue by shalstvedt** [AskNature/AN#105]
Since they don't have a name, they can't be created (they have a headline). This might open up a larger discussion about making these consistent, but for now removing the 'name' constraint will suffice.

**Comment by ethansmith** [comment]
I'm going to make a wholesale change now to make these consistent with everything else.

**Comment by shalstvedt** [comment]
Ah, ok. I started to remove the name constraint, but it also required a bit of logic in stores (to set the masterid correctly), so I think that's a better approach. Thanks!

**Comment by ethansmith** [comment]
Changed in 198a3e4.
