### ISSUE TITLE
HIGH: Image not displaying on Designed System

### ISSUE THREAD

**Issue by jlschill** [AskNature/AN#140]
I just connected this image (<p>Chaac...) to this record (http://asknatu.re/d.system/chaac-ha-water-system-collector). Though showing in edit mode as linked, it's not displaying for me.

**Comment by shalstvedt** [comment]
@jlschill this image appears broken in our original data import. I can fix it

**Comment by shalstvedt** [comment]
Or @ethansmith if you wanted to take care of this that would work too

**Comment by ethansmith** [comment]
I'm on it.
