### ISSUE TITLE
Can't connect R&D Team to Designed System

### ISSUE THREAD

**Issue by jlschill** [AskNature/AN#144]
Trying to connect Team Panteras to this record, it won't even let me click the + sign:
http://asknatu.re/d.system/chaac-ha-water-system-collector

(Perhaps when Ethan noted to me that the Team add functionality needed to be fixed when we discussed Sources, this is universal?)

**Comment by ethansmith** [comment]
on it.

**Comment by ethansmith** [comment]
fixed.
