### ISSUE TITLE
HIGH: Appears to be dup record

### ISSUE THREAD

**Issue by jlschill** [AskNature/AN#150]
Of this one (one version w/ paragraph tags, other w/out):
http://asknatu.re/d.strategy/lesspgreaternanostructures-boost-water-droplet-motionslesspgreater

**Comment by jlschill** [comment]
the <p> record, at quick glance, appears to be slightly more complete/connected.

**Comment by shalstvedt** [comment]
The record no longer exists. Closing this issue.
