### ISSUE TITLE
Admin list filters return NULL when chars removed & unpredictable overall

### ISSUE THREAD

**Issue by ethansmith** [AskNature/AN#26]
In tests of the strategy filter, a null set of results is returned when there are <=2 characters remaining as a query is being deleted. in general, as characters are added/deleted after initial (additive) input, results are hit and miss.

**Comment by ethansmith** [comment]
Also, the last character of a filter string doesn't seem to register. For instance, the string "foobar" will return all results that contain "fooba".

**Comment by ethansmith** [comment]
Also, count and pagination #'s don't update with filter

**Comment by shalstvedt** [comment]
Have a fix on https://github.com/AskNature/AN/tree/generic-flux
