### ISSUE TITLE
Left drawer incompatibilities

### ISSUE THREAD

**Issue by ethansmith** [AskNature/AN#31]
Left nav drawer doesn't work in safari.

**Comment by ethansmith** [comment]
Also, left nav drawer needs to close when it loses focus and behave better on narrow screens.

**Comment by ethansmith** [comment]
Fixed safari incompatibility. 

Drawer still needs to automatically close when tapped on small screens. I think this will be easier to implement after Scott consolidates infinite/detail code.

**Comment by shalstvedt** [comment]
@ethansmith: agreed. Should be a trivial change but it will be smart to do it once everything is in its final resting place.
