### ISSUE TITLE
Logging in doesn't affect navbar conditional user menu

### ISSUE THREAD

**Issue by ethansmith** [AskNature/AN#39]
...although authentication still seems to be working...

**Comment by shalstvedt** [comment]
Hmm... I agree, it's still getting the proper user object, but /login should redirect to the homepage if logged in and that isn't happening either. Will investigate.

**Comment by ethansmith** [comment]
Conditional fixed. 

Regarding your second point, a few weeks back I set the /login event to go back to the previous browser history state (back to where the user started). However, it obviously doesn't work well if the user navigates from /login to /signup. Low priority task may be to record what URL user was on before diving into account creation and send them back there. A topic for another thread, though. I'm closing this one.
