### ISSUE TITLE
status selection doesn't propagate to db via setRelationship

### ISSUE THREAD

**Issue by ethansmith** [AskNature/AN#48]

**Comment by ethansmith** [comment]
this applies to other relationships as well using addRelationship and removeRelationship

**Comment by ethansmith** [comment]
Scott, you're right ... this still works on your search-list branch. I'll figure out the diff and return master to working order.

**Comment by shalstvedt** [comment]
Sounds good... let me know if it's taking too much of your time and I can help find it.

**Comment by shalstvedt** [comment]
Did we get this figured out?

**Comment by ethansmith** [comment]
it was working .. and then not again. i'm still having issues in master.

**Comment by shalstvedt** [comment]
Righto, it's not working for me in master either. Will hunt down.



On Wed, Apr 15, 2015 at 12:20 PM -0700, "Ethan Smith" <notifications@github.com> wrote:












Assigned #48 to @shalstvedt.

**Comment by shalstvedt** [comment]
Working
