### ISSUE TITLE
Drawer and search icon appear as emoji in iOS Safari

### ISSUE THREAD

**Issue by shalstvedt** [AskNature/AN#64]
A picture is worth 1000 words:

![img_3030](https://cloud.githubusercontent.com/assets/129513/7142186/ec93e5ce-e293-11e4-8634-d88b84f8acf0.PNG)

**Comment by ethansmith** [comment]
that's rather fantastic. I'm actually intending to make a wholesale move to fontawesome icons rather than being split between fontawesome and glyphicons as we are now. perhaps i'll make that happen sooner than later...

**Comment by shalstvedt** [comment]
Whenever it makes sense. Just thought you'd get a kick out of this one :smiley:

**Comment by ethansmith** [comment]
Meanwhile, those icons don't even appear in old versions of Android's native browser.

**Comment by ethansmith** [comment]
All icons have been changed to fontawesome.
