### ISSUE TITLE
Entering a <space> at end of content in editable fields sends cursor back to beginning of field.

### ISSUE THREAD

**Issue by ethansmith** [AskNature/AN#71]

**Comment by shalstvedt** [comment]
This is interesting... we haven't been mucking with the scribe stuff AFAIK

**Comment by shalstvedt** [comment]
The fields are also REALLY slow

**Comment by shalstvedt** [comment]
Typing in a field appears to trigger ~6 re-renders of component-detail.

**Comment by shalstvedt** [comment]
OK, call me crazy... but this works fine in 0f32a5a3df4ef587bf0021ad61a4ada852a7f358 but is broken in 1a6ebec779b4da17b476905b0356a54f0735939b. This makes absolutely no sense.

**Comment by shalstvedt** [comment]
Fixed in 7ea4d2d300046385a9d170a1bf02b0033f59ef8d
