### ISSUE TITLE
Dropdown icons are missing on relationship editor in Chrome

### ISSUE THREAD

**Issue by shalstvedt** [AskNature/AN#74]
![image](https://cloud.githubusercontent.com/assets/129513/7196332/50ac5bb8-e48d-11e4-956c-b32de127cb04.png)

Chrome 41.0.2272.118 OS X. Seems to work in Safari. Also, perhaps unrelated, but several 404s in console as well.

**Comment by ethansmith** [comment]
Yep.. this is on my to-do list.

**Comment by ethansmith** [comment]
Fixed in e8827ba and 4d459a3. 404s were unrelated, but are fixed in this commit as well.
