### ISSUE TITLE
On browser refresh, components load before user loggedin conditionals run

### ISSUE THREAD

**Issue by ethansmith** [AskNature/AN#75]
For instance, if I'm logged in and looking at a detail view and refresh, I lose editing capabilities and can't see the table view. I'm I'm looking at an admin list I can't see the 'delete' button anymore

**Comment by shalstvedt** [comment]
Same as #73

**Comment by shalstvedt** [comment]
But good to know this is elsewhere besides detail views

**Comment by ethansmith** [comment]
Oh.. didn't notice that, but you're right. Closing this issue in favor of #73 .
