### ISSUE TITLE
Navbar user avatar padding is incorrect on production, but renders correctly locally.

### ISSUE THREAD

**Issue by ethansmith** [AskNature/AN#83]
Linked to issue #82.

**Comment by shalstvedt** [comment]
This renders incorrectly on my local environment as well as production

**Comment by ethansmith** [comment]
Thanks.. that should make this slightly easier to track down.

**Comment by ethansmith** [comment]
Interesting.. This is how the react-bootstrap DropdownButton renders locally for me:

![image](https://cloud.githubusercontent.com/assets/3789432/7259608/4d6ab9c4-e819-11e4-9a63-33f589fab667.png)

and this is how it renders on production:

![image](https://cloud.githubusercontent.com/assets/3789432/7259625/64d769ae-e819-11e4-9543-4645ef63d341.png)

Thus, the specific css rules that work on on the former don't work on the latter.

Any idea why this might be happening to me and not you?
