### ISSUE TITLE
Common name of Living System not displaying

### ISSUE THREAD

**Issue by jlschill** [AskNature/AN#92]
We ideally want it to display at least for this record for Copenhagen demo: http://asknatu.re/b.system/1909 (Actinopterygii). Thanks!

**Comment by shalstvedt** [comment]
Thanks Jen!

**Comment by shalstvedt** [comment]
And the common name for this would be "ray-finned fishes"?

**Comment by ethansmith** [comment]
The eventual goal is to return everything in the `name` fields to the linnaean latin names, and scrape the common names via EOL's API. In the meantime, I'll make sure that the `common_name` field is used if there's anything in it, and fall back to just listing "Common Name". I'll also add "Ray-finned Fishes" as the common name for Actinopterygii.
