### ISSUE TITLE
Scribe text fields wrap content in <p>

### ISSUE THREAD

**Issue by shalstvedt** [AskNature/AN#95]

**Comment by shalstvedt** [comment]
Seems to happen on copy-and-paste

**Comment by shalstvedt** [comment]
@ethansmith I'm having trouble reproducing this for any case other than when the entirety of the field is pasted into.

**Comment by ethansmith** [comment]
I'm experiencing the same. Pasting content puts it into a <p class="p1"></p> container that's impossible to remove right now except via the raw string in the db. 

This is related to #96, since the p.p1 style class makes the field display twice when `editable = true`.
