### ISSUE TITLE
Scribe long-form fields don't properly hide content when editing

### ISSUE THREAD

**Issue by shalstvedt** [AskNature/AN#96]
Seems to work on test strategies, but at http://asknatu.re/d.strategy/air-ballast-biomimetic-cargo-ship it shows the field twice when editing. Perhaps a consequence of embedded content?

**Comment by ethansmith** [comment]
I noticed this too ... but before i added the embedded content. I'm not sure why this phenomenon is limited to this component.

**Comment by shalstvedt** [comment]
This doesn't seem to have an easy diagnosis... let me know if you can think of any common properties between affected items.

**Comment by ethansmith** [comment]
Related to #95. p.p1 style class is the culprit, but I'm not sure why.

**Comment by shalstvedt** [comment]
fixed in 62b8b63
